name: Issue Auto Comment

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: 이슈 안내 댓글 등록
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '이슈가 생성되었습니다. 담당자와 라벨이 자동으로 지정됩니다. 감사합니다!'
            }) 