name: PR Reviewer

on:
  pull_request:
    types: [opened]

jobs:
  reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: PR 코드 리뷰어 자동 지정
        uses: ahmadnassri/action-auto-assign-reviewers@v2.0.0
        with:
          reviewers: ihkim-secret 